INSERT INTO angielski (question_content, question_answer_1, question_answer_2, question_answer_3, question_answer_4, question_correct ) VALUES
('Look at those ...', 'bird ', 'birds'' ', 'birds ', 'bird''s', 3),
('This is ... dog', 'mine ', 'my ', 'me', 'I', 2),
('Do you like Tom? Yes, I really like ... .', 'her ', 'his ', 'hers ', 'him', 4),
('Caroline ... a big flat.', 'has got ', 'have got ', 'hasn''t ', 'haven''t', 1),
('... a cat on the sofa.', 'There are ', 'They are ', 'There is ', 'They is', 3),
('A: ... is this woman? B: She''s ... .', 'What ... teacher', 'When ... 68', 'How ... 68', 'Who ... a teacher', 4),
('The show is .. Friday ... 8 o''clock.', 'on ... at', 'in ... on ', 'at ... on', 'on ... in', 1),
('Thanks very much for your help.', 'Yeah.', 'You''re welcome.', 'That''s a pity.', 'Bless you.', 2),
('My father usually ... to the radio in the morning.', 'is listening ', 'listen ', 'listens ', 'are listening', 3),
('Taylor is in his room. I think he ... his homework now.', 'does ', 'is doing ', 'do', 'are doing', 2),
('... cheese is there in the fridge?', 'How much ', 'How many ', 'How lot of ', 'How old', 1),
('There is a table ... the sofa and the armchair.', 'under ', 'on ', 'over ', 'between', 4),
('My children like ... computer games.', 'play ', 'playing ', 'played ', 'to playing', 2),
('It''s the ... house. They are very friendly.', 'Johnsons'' ', 'Johnson''s ', 'Johnsons ', 'Johnson', 1),
('Where is ... mountain in the world?', 'high ', 'the high ', 'higher ', 'the highest', 4),
('This book is more interesting ... the other one.', 'then ', 'that ', 'than ', 'to', 3),
('I''m looking ... my lighter. Have you seen it?', 'at ', 'for ', 'after ', 'over', 2),
('A one-month-old baby ... read.', 'should ', 'can''t ', 'mustn''t ', 'ought to', 2),
('When you drive a car, you ... be very careful.', 'have ', 'had ', 'has to ', 'have to', 4),
('I don''t want apples ... bananas.', 'or', 'and ', 'but ', 'to', 1),
('When ... born?', 'did you be ', 'were you ', 'you were ', 'did you', 2),
('When ... school?', 'did you finish ', 'were you finish ', 'you finished ', 'did you finished', 1),
('He ... yesterday and ... about you.', 'comes ... asks ', 'comed ... asked ', 'come ... ask ', 'came ... asked', 4),
('Albert Einstein ... speak until he was eight.', 'can''t ', 'can ', 'couldn''t ', 'not could', 3),
('... to Paris?', 'Has he ever been ', 'Has he ever was ', 'Were he ever ', 'Is he ever been', 1),
('I have known Ian ... 10 years.', 'from ', 'for ', 'since ', 'in', 2),
('A: What are you doing next weekend? B: I don''t know yet. Maybe I ... to the cinema.', 'am going ', 'am going to go ', 'will go ', 'go', 3),
('They are really in love and they ... married next month.', 'will getting ', 'are getting ', 'are going ', 'going to get', 2),
('I don''t want ... on Saturday.', 'work ', 'to work ', 'working ', 'worked', 2),
('When I ... dinner, somebody knocked at the door.', 'cooked ', 'have cooked ', 'am cooking ', 'was cooking', 4),
('This book ... by my favourite author.', 'wrote ', 'written ', 'was written ', 'was wrote', 3),
('What is she like?', 'She likes bananas. ', 'She isn''t. ', 'She is tall and pretty. ', 'She is hard-working.', 4),
('A photographer is a person ... takes pictures.', 'who ', 'which ', 'whose ', 'whom', 1),
('A: I don''t like horror films. B: ... .', 'So do I. ', 'Neither do I. ', 'I don''t too. ', 'I do too.', 2),
('Who ... their house?', 'did renovate ', 'did renovation ', 'was renovated ', 'renovated', 4),
('I always try to ... something each month for my holidays.', 'spare ', 'save ', 'spend ', 'charge', 2),
('I have no brothers or sisters. I am ... child.', 'an only ', 'a sole ', 'a single ', 'a one', 1),
('I was very ... in that film, but it was actually very ... .', 'interesting ... boring ', 'interested ... bored ', 'interesting ... bored ', 'interested ... boring' , 4),
('They used to ... in London, but now they live in Helsinki.', 'living ', 'live ', 'lives ', 'lived', 2),
('The house was dirty. They ... it for weeks.', 'haven''t cleaned ', 'didn''t clean ', 'hadn''t cleaned ', 'weren''t cleaning', 3),
('Jane''s coming to see you, ...?', 'hasn''t she ', 'doesn''t she', 'wasn''t she ', 'isn''t she', 4),
('You look exhausted. What ... ?', 'have you been doing ', 'did you do ', 'have you done ', 'had you done', 1),
('Please call me as soon as you ... home.', 'will get ', 'get ', 'will be getting ', 'got', 2),
('If he ... the driving test, he ... a car.', 'will pass ... will buy ', 'passes ... will buy ', 'will pass ... buys ', 'passes ... buys', 2),
('What ... if you ... a lot of money?', 'would you do ... win ', 'did you do ... don''t win ', 'would you do ... won ', 'did you do ... won', 3),
('Excuse me, do you know where ... ?', 'the nearest bank is ', 'is the nearest bank ', 'will the nearest ', 'would the', 1),
('Our house ... last month.', 'burgled ', 'was burgle ', 'has been burgled ', 'was burgled', 4),
('"I don''t want to do this". He said ... .', 'he didn''t want to do that ', 'he don''t want to do that ', 'he doesn''t want to do this ', 'he hasn''t wanted to do that', 1),
('"Are you a vegetarian?". She asked me ... a vegetarian.', 'was I ', 'if I was ', 'whether was I ', 'if was I', 2),
('"Stop interrupting me!". He told me ... interrupting him.', 'that I stopped ', 'I must stop ', 'stop ', 'to stop', 4),
('You should have more confidence. You are ... attractive person.', 'so an ', 'so ', 'such a', 'such an', 4),
('... asking him to dinner?', 'Why don''t we ', 'How about ', 'Shall we ', 'Let''s', 2),
('I prefer apples ... bananas.', 'to ', 'than ', 'rather ', 'that', 1),
('They can''t ... abroad this summer.', 'afford ', 'afford going ', 'afford to go ', 'to have gone', 3),
('Would you mind ... the radio down?', 'turning ', 'turn ', 'to turn', 'to have turned', 1),
('The teachers in my school made us ... .', 'learn everything by heart ', 'to memorize everything', 'to learn a lot ', 'to study all the time', 1),
('I wasn''t tired last night. If I had been tired, I ... home earlier.', 'would go ', 'would have gone ', 'will go ', 'went', 2),
('... I set my alarm clock for 7 am, it didn''t go off.', 'Despite ', 'In spite of the fact', 'However', 'Although', 4),
('Her jacket is dirty. It needs ... .', 'to be clean ', 'cleaning ', 'clean ', 'being clean', 2),
('Try ... this medicine, it might help you.', 'to take ', 'to have taken ', 'taking ', 'having taken', 3),
('How often do you ...?', 'have your car serviced ', 'have your car service ', 'have your car being serviced ', 'have your car had serviced', 1),
('Why was he arrested? He''s said ... a policeman.', 'to have kicked ', 'to kick ', 'kicked ', 'having kicked', 1),
('I feel very full after that meal. I''m not used ... so much.', 'to eat ', 'to eating ', 'to be eating', 'to have eaten', 2),
('... (P, ) people are complaining because ... governor has stopped ... construction of ... new hospital.', 'The ... - ... the ... a ', '- ... the ... the ... a', '- ... a ... the ... a ', 'The ... a ... the ... -' , 2),
('Tom hasn''t come to class for two weeks, ... is a bit worrying.', 'which ', 'what ', 'whom ', 'whose', 1),
('What do the letters N.U.T. ... ?', 'stand up ', 'stand for ', 'get off ', 'get to', 2),
('"I won''t do it." She ... .', 'refused doing it ', 'persuaded to do it ', 'persuaded doing it ', 'refused to do it', 4),
('I am supposed to deliver the speech at 3pm, ... ?', 'aren''t I ', 'am I not ', 'I am not ', 'am I', 1),
('We ... for petrol soon. The tank is almost empty.', 'would better stop ', 'had better stop ', 'would stop ', 'had stopped', 2),
('I''m almost done with my work, next week at this hour I ... on the beach.', 'will lie ', 'will have lain ', 'am lying ', 'will be lying', 4),
('I ... all my exams by June, so we can go on holiday then.', 'will have passed ', 'will pass ', 'will be passing ', 'will have been passing', 1),
('By next Christmas we ... together for 10 years.', 'will work ', 'are going to work ', 'will have been working ', 'have worked', 3),
('We ... for about 2 hours when the captain told us to fasten our seatbelts.', 'have been flying ', 'had been flying ', 'will be flying ', 'were flying', 2),
('Have you seen this ... skirt? It''s gorgeous!', 'long striped silk ', 'striped long silk ', 'long silk striped ', 'silk long striped', 1),
('Call them later, they ... now.', 'might be sleeping ', 'can''t be sleeping ', 'must have slept', 'shouldn''t be sleeping', 1),
('They ..., the lights are off.', 'can''t have gone out ', 'must have gone out ', 'must be at home ', 'should have been at home', 2),
('"We won''t be able to pay until next week". They said they ... be able to pay until ... week.', 'wouldn''t ... the following ', 'won''t ... the following', 'wouldn''t ... the next ', 'won''t ... the next', 1),
('They won''t get married ... he gets a job. They need financial security first.', 'if ', 'unless ', 'while ', 'whereas', 2),
('Make sure you know about visa regulations in case ... one.', 'you will need ', 'you have needed ', 'you need ', 'you are needing', 3),
('We regret ... you that there are no seats on the 12.30 flight.', 'informing ', 'to inform ', 'to be informing ', 'having inform', 2),
('Laura ... my appearance. It''s annoying.', 'always criticises ', 'has been always criticising ', 'always is criticising ', 'is always criticising', 4),
('I''d like to thank you all ... my husband, who can''t be here today.', 'on behalf of ', 'on account of ', 'in spite of ', 'due to', 1),
('I wish I ... you, you''ve got such excellent ideas.', 'were ', 'had been ', 'would be ', 'can be', 1),
('I''d rather you ... in your room. You usually leave the dirty dishes there.', 'hadn''t eaten ', 'didn''t eat ', 'not eat ', 'don''t eat', 2),
('Don''t you think it''s high time you ... a job?', 'would find ', 'found ', 'had found ', 'find', 2),
('It''s no use ... Tom. He won''t be able to help us.', 'in trying ', 'to ask ', 'to try', 'asking',4 ),
('Not only ... lazy, but ... very selfish.', 'is he ... he''s also ', 'he is ... he also is ', 'is he ... he also is ', 'he is ... he''s also', 1),
('I ... in this situation now if I ... to your advice the last time.', 'wouldn''t have been ... listened ', 'wouldn''t be ... had listened ', 'wouldn''t have been ... had listened ', 'wouldn''t be ... listened', 2),
('She wishes it ... snowing.', 'would stop ', 'stops ', 'had stopped ', 'has stopped', 1),
('Hardly ... when the train began to move.', 'would I sit down ', 'did I sit down ', 'had I sat down ', 'I sat down', 3)
